export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS";
export const FETCH_MOVIES_FAILURE = "FETCH_MOVIES_FAILURE";
export const FETCH_MOVIES_REQUEST = "FETCH_MOVIES_REQUEST";
export const SEARCH_MOVIES = "SEARCH_MOVIES";
export const FETCH_MOVIE_INFO_SUCCESS = "FETCH_MOVIE_INFO_SUCCESS";
export const FETCH_MOVIE_INFO_FAILURE = "FETCH_MOVIE_INFO_FAILURE";
export const TOGGLE_MOVIE_INFO_MODAL = "TOGGLE_MOVIE_INFO_MODAL";
